Add low-privilege postgres roles for Explorer
opendatacube/datacube-explorer pull request #175
Opened 2020-08-03 05:48 UTC by jeremyh

(hopefully) fixes  #168

This adds several plain-sql scripts for adding roles. (see the readme below for explanation)

These are separated into several scripts to cater to the many different Explorer setups (NCI, AWS, Local, Existing, Brand-New), which all have slightly different existing permissions and needs.

But generally a user just runs them in order. The first few will fail if they already have some things, which is okay. Each script is done in a separate transaction.

There are no tests because tests seem like they'd be a nightmare to set-up with our current CI, unfortunately. We will have to be careful with future changes. But at least errors will be loud.  Locally I've tested these scripts on both an existing Explorer and a brand-new one.

(Note: I strongly considered making this another Python command, so that we could use variables and avoid repetition of the schema elements, but I decided simplicity of plain-sql is better due to the diversity of security requirements. All environments that I know of allow running or pasting-in plain SQL. And these are run by an Admin, so should be rare and simple.)

2020-08-06 10:59 UTC, whatnick requested changes
Small typo .. great otherwise. Perhaps some docs around bootstrapping and migrating.

2020-08-06 10:59 UTC, whatnick commented on README.md
> +role is available as a prerequisity in the same [roles](cubedash/summary/roles)
Small typo `prerequisite`

2020-08-06 22:18 UTC, jeremyh commented on README.md
> +role is available as a prerequisity in the same [roles](cubedash/summary/roles)
Thanks -- fixed

2020-08-20 01:41 UTC, whatnick approved these changes

2020-08-20 03:43 UTC, merged