Parse NCI filepaths to THREDDS location
opendatacube/datacube-explorer pull request #523
Opened 2023-03-03 05:25 UTC by Ariana-B

As per #520

2023-03-05 21:50 UTC, dunkgray approved these changes
looks ok, though I haven't worked on this code.

2023-03-05 23:25 UTC, omad requested changes
Hi Ariana,

Can you please make this an opt-in/configurable option. Explorer isn't only used by DEA, and this change would be most unexpected in other environments. :)

Cheers

2023-03-18 00:56 UTC, mpaget commented
> an opt-in/configurable option

Yes, I expect this would be good to have configurable by a deployment admin. Sharing some ideas, if helpful.

If URL converting regexs or functions were imported from `settings.env.py` we'd need to consider the security implications and do some careful vetting. I'm not sure of the effort or appetite to look at it from that perspective. A transparent in-code solution would be easier.

As a deployment patch perhaps? Perhaps `settings.env.py` could reference an `as_external_url` function that can be imported by explorer, else the "s3" default is used. The custom `as_external_url` function would need to be uploaded to the host running explorer. This may require an update to the explorer chart too.

2023-04-01 00:34 UTC, whatnick commented
Could we please update this to latest develop to avoid potential `merge with rebase` issues, especially if global settings are being changed. This will affect the main file where the timezone setting was recently added.

2026-06-19 07:50 UTC, omad commented
Feel free to re-open, but I suspect this is no longer particularly useful, or applicable.

2026-06-19 07:50 UTC, closed without merging